const books=[
    {title:"Things Fall", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},
    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},

    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},

    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},

    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},

    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},

    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},

    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},

    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},

    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},

    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},

    {title:"Things Fall Apart", author:"Chinedu", publication:"25/03/2022", type:"Fiction"},

]

module.exports=books